theme: jekyll-theme-dinky
title: The homepage of Anna Maria Feriozzi
description: What you will find here are links to projects, publications, and repositaries related to the former. 
plugins: 
- jemoji
url: "http://annamariaferiozzi.github.io/"
markdown: kramdown
